server:
  port: 8001
mybatis:
  type-aliases-package: com.yuan.springcloud.pojo
  #  mybatis核心配置文件
  config-location: classpath:mybatis/mybatis-config.xml
#  mybatis映射文件
  mapper-locations: classpath:mybatis/mapper/*.xml #配置mybatis配置文件路径


#spring配置
spring:
  application:
    name: springcloud-provider-dept #服务名字
#
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db01?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root

#Eureka配置,服务注册地址
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001:7001/eureka/,http://eureka7002:7002/eureka/,http://eureka7003:7003/eureka/
  instance:
    instance-id: springcloud-provider-dept8001 #修改eureka默认藐视信息
    prefer-ip-address: true #显示服务ip

#eureka的服务info信息配置 需要导入actutor包
info:
  app.name: yuan-springcloud
  company.name: www.baidu.com

