server:
  port: 7003
eureka:
  instance:
    hostname: eureka7003 #eureka服务端名字
  client:
    register-with-eureka: false #表示是否向eureka注册中心注册自己
    fetch-registry: false #如果为false，则表示自己为注册中心
    service-url: #监控页面
      defaultZone: http://eureka7001:7001/eureka/,http://eureka7002:7002/eureka/